name: Build & Export

on:
  push:
    tags: ["*"]

jobs:
  export_game:
    name: Export Game
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: checkout
        uses: actions/checkout@v6
        with:
          submodules: recursive

      - name: setup & build GDExtension
        uses: NodotProject/godot-cpp-builds@v1
        with:
          godot-version: '4.5-stable'
          godot-cpp-path: './src/godot-cpp'

      - name: Install Build Essentials
        run: |
          sudo apt-get update
          sudo apt-get install -y scons build-essential

      - name: Install Windows compiler
        run: |
          sudo apt-get install -y g++-mingw-w64

      - name: Setup emsdk
        uses: mymindstorm/setup-emsdk@v14
        with:
          version: 3.1.64
          actions-cache-folder: 'emsdk-cache'

      - name: Verify Emcc
        run: emcc -v

      - name: Emcc Cache
        uses: actions/cache@v5
        with:
          path: |
            'emsdk-cache'
          key: 3.1.64-${{ runner.os }}

      - name: SCons Cache
        uses: actions/cache@v5
        with:
          path: |
            ${{ env.PROJECT_PATH }}/.sconsign.dblite
            ${{ env.PROJECT_PATH }}/godot-cpp/gen/
            ${{ env.PROJECT_PATH }}/bin/
          key: ${{ runner.os }}-scons-${{ hashFiles('src/SConstruct', 'src/src/**') }}
          restore-keys: |
            ${{ runner.os }}-scons-

      - name: Compile to three platforms
        working-directory: src
        run: |
          scons platform=linux target=template_release || true
          scons platform=windows target=template_release || true
          scons platform=web target=template_release || true

      - name: Verify Binaries
        run: ls -R src/bin/

      - name: export game
        id: export

        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_export_templates.tpz
          relative_project_path: ./src/
          archive_output: true

      - name: create release
        uses: ncipollo/release-action@v1.18.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: false
          draft: true
          tag: ${{ github.ref_name }}
          artifacts: ${{ steps.export.outputs.archive_directory }}/*
