name: Export & Deploy

on:
  push:
    tags: ["*"]

jobs:
  export:
    name: Export Game
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      # prevent re-downloadnig godot & its templates
      - name: Godot download cache
        uses: actions/cache@v5
        with:
          path: |
            ~/.local/share/godot/
          key: godot-4.6.1-stable-templates

      - name: Godot Export
        id: export
        uses: firebelley/godot-export@v7.0.0
        with:
          godot_executable_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_linux.x86_64.zip
          godot_export_templates_download_url: https://github.com/godotengine/godot/releases/download/4.6.1-stable/Godot_v4.6.1-stable_export_templates.tpz
          relative_project_path: ./src/
          archive_output: true
          cache: true

      - name: Upload zipped artifacts
        uses: actions/upload-artifact@v7
        with:
          name: exported-zips
          path: ${{ steps.export.outputs.archive_directory }}/*.zip

  deploy:
    name: Deploy to GitHub and Itch
    needs: export
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Download zips
        uses: actions/download-artifact@v8
        with:
          name: exported-zips
          path: out/

      - name: Github Release
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          tag: ${{ github.ref_name }}
          draft: false
          artifacts: out/*.zip

      - name: Install Butler
        run: |
          curl -L -o butler.zip https://broth.itch.zone/butler/linux-amd64/LATEST/archive/default
          unzip butler.zip
          chmod +x butler
          ./butler -V

      - name: Deploy to Itch.io
        env:
          BUTLER_API_KEY: ${{ secrets.ITCHIO_TOKEN }}
        run: |
          ./butler push out/Linux.zip favem-s-davem/favem-s-davem:linux --userversion=${{ github.ref_name }} || true
          ./butler push out/Windows\ Desktop.zip favem-s-davem/favem-s-davem:windows --userversion=${{ github.ref_name }} || true
          ./butler push out/Web.zip favem-s-davem/favem-s-davem:web --userversion=${{ github.ref_name }} || true
          ./butler push out/macOS.zip favem-s-davem/favem-s-davem:macos --userversion=${{ github.ref_name }} || true
